import {
  HTML5Icon,
  CSS3Icon,
  JavaScriptIcon,
  TypeScriptIcon,
  ExpressIcon,
  FigmaIcon,
  GitHubIcon,
  NodeJsIcon,
  PostgreSQLIcon,
  ReactIcon,
  SassIcon,
  SequelizeIcon,
  TailwindCSSIcon,
  TrelloIcon,
  VSCodeIcon,
  ViteJsIcon,
  NotionIcon,
  CommunicationIcon,
  TeamIcon,
  CookieIcon,
  OrganisationIcon,
  CuriosityIcon,
} from "../../assets/skills_icons";

export const iconMapping: { [key: string]: string } = {
  HTML5: HTML5Icon,
  CSS3: CSS3Icon,
  JavaScript: JavaScriptIcon,
  TypeScript: TypeScriptIcon,
  Express: ExpressIcon,
  Figma: FigmaIcon,
  GitHub: GitHubIcon,
  "Node.js": NodeJsIcon,
  PostgreSQL: PostgreSQLIcon,
  React: ReactIcon,
  Sass: SassIcon,
  Sequelize: SequelizeIcon,
  "Tailwind CSS": TailwindCSSIcon,
  Trello: TrelloIcon,
  VSCode: VSCodeIcon,
  "Vite.js": ViteJsIcon,
  Notion: NotionIcon,
  Communication: CommunicationIcon,
  Team: TeamIcon,
  Cookie: CookieIcon,
  Organisation: OrganisationIcon,
  Curiosity: CuriosityIcon,
};
