export { default as HTML5Icon } from './HTML5.svg';
export { default as CSS3Icon } from './CSS3.svg';
export { default as JavaScriptIcon } from './JavaScript.svg';
export { default as TypeScriptIcon } from './TypeScript.svg';
export { default as ExpressIcon } from './Express.svg';
export { default as FigmaIcon } from './Figma.svg';
export { default as GitHubIcon } from './GitHub.svg';
export { default as NodeJsIcon } from './Node.js.svg';
export { default as PostgreSQLIcon } from './PostgresSQL.svg';
export { default as ReactIcon } from './React.svg';
export { default as SassIcon } from './Sass.svg';
export { default as SequelizeIcon } from './Sequelize.svg';
export { default as TailwindCSSIcon } from './Tailwind CSS.svg';
export { default as TrelloIcon } from './Trello.svg';
export { default as VSCodeIcon } from './Visual Studio Code (VS Code).svg';
export { default as ViteJsIcon } from './Vite.js.svg';
export { default as NotionIcon } from './Notion.svg';
export { default as CommunicationIcon } from './Communication.svg';
export { default as TeamIcon } from './Team.svg';
export { default as CookieIcon } from './Cookies.svg';
export { default as OrganisationIcon } from './Organisation.svg';
export { default as CuriosityIcon } from './Curiosity.svg';
